# Generated by Django 3.1.1 on 2020-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='Post_image'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='userimage'),
        ),
    ]
